#!/bin/bash

TUNNEL_USER=${TUNNEL_USER:-berto}
TUNNEL_HOST=${TUNNEL_HOST:-sprocketlight.com}
SSH_PORT=${SSH_PORT:-22022}
IDENTITY=${IDENTITY:-/home/berto/.ssh/no_pw}

TEST_LOG=${TEST_LOG:-/var/log/tunnel_test.log}

USER=$(whoami)
    
function tunnel
{
    while [ 1 ];
        do date;
        ssh -N \
            -i ${IDENTITY} \
            -o ServerAliveInterval=60 \
            -o BatchMode=yes \
            -R ${SSH_PORT}:localhost:22 ${TUNNEL_USER}@${TUNNEL_HOST};
        sleep 5;
    done;
}

function test
{
    stuff=$(ssh -p ${SSH_PORT} ${TUNNEL_HOST} 2>&1)
    echo $stuff | grep -q -i 'permission denied'
    status=$?
    #stuff=$(nc -w 5 ${TUNNEL_HOST} ${SSH_PORT})
    #echo $stuff | grep -q OpenSSH
    #status=${PIPESTATUS[1]}

    #echo "status ${status}"

    if [ "$status" != "0" ]; then
        /sbin/stop tunnel &> /dev/null
        /sbin/start tunnel &> /dev/null
        echo "($USER) $(date): restarted tunnel" >> ${TEST_LOG}
    else
        echo "all good" > /dev/null
    fi;
}

if [ "$1" == "test" ]; then
    test
else
    tunnel
fi;
