#!/bin/bash

# source local configuration
REVERSE_TUNNEL_CONF=/etc/default/reverse_tunnel
[ -e ${REVERSE_TUNNEL_CONF} ] && source ${REVERSE_TUNNEL_CONF}

TUNNEL_USER=${TUNNEL_USER:-tunnel}
USER=$(whoami)

SSH_PORT=${SSH_PORT:-22022}
IDENTITY=${IDENTITY:-/home/tunnel/.ssh/id_rsa}
LOGFILE=${LOGFILE:-/var/log/reverse_tunnel.log}

[ -z ${TUNNEL_HOST} ] && echo "need to specify TUNNEL_HOST in environment" 1>&2 && exit 1

function tunnel
{
    while [ 1 ];
        do date;
        ssh -N \
            -i ${IDENTITY} \
            -o ServerAliveInterval=60 \
            -o BatchMode=yes \
            -R ${SSH_PORT}:localhost:22 ${TUNNEL_USER}@${TUNNEL_HOST};
        sleep 5;
    done;
}

function test
{
    output=$(ssh -p ${SSH_PORT} ${TUNNEL_HOST} 2>&1)
    echo $output | grep -q -i 'permission denied'
    status=$?
    #echo "status ${status}"

    if [ "$status" != "0" ]; then
        /sbin/stop tunnel &> /dev/null
        /sbin/start tunnel &> /dev/null
        echo "($USER) $(date): restarted tunnel" >> ${LOGFILE}
    fi;
}

if [ "$1" == "test" ]; then
    test
else
    tunnel
fi;
